# Generated by Django 2.2.6 on 2019-10-30 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='APP介绍')),
                ('image', models.ImageField(default='', upload_to='photos/%Y/%m/%d/', verbose_name='App图片')),
                ('android_url', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='安卓下载地址')),
                ('ios_url', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='苹果下载地址')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='奖励属主')),
            ],
            options={
                'verbose_name': 'App介绍',
                'verbose_name_plural': 'App介绍',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(default='', max_length=128, verbose_name='中文名')),
                ('image', models.ImageField(default='', upload_to='photos/%Y/%m/%d/', verbose_name='头像')),
                ('school', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='学校')),
                ('street', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='街道地址')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='电子邮箱')),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='电话')),
                ('qq', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='qq')),
                ('wechat', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='微信')),
                ('content', models.TextField(default='', verbose_name='自我介绍')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200, verbose_name='个人技能')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('program_language', models.CharField(max_length=50, verbose_name='编程语言')),
                ('skill_explain', models.CharField(max_length=200, verbose_name='技能说明')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='技能属主')),
            ],
            options={
                'verbose_name': '技能介绍',
                'verbose_name_plural': '技能介绍',
            },
        ),
        migrations.CreateModel(
            name='interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='兴趣介绍')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='兴趣属主')),
            ],
            options={
                'verbose_name': '兴趣介绍',
                'verbose_name_plural': '兴趣介绍',
            },
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='特性名称')),
                ('content', models.CharField(max_length=200, verbose_name='特性介绍')),
                ('icon', models.CharField(choices=[('icon-screen-smartphone', 'icon-screen-smartphone'), ('icon-camera', 'icon-camera'), ('icon-present', 'icon-present'), ('icon-lock-open', 'icon-lock-open')], default='icon-screen-smartphone', max_length=200, verbose_name='特性图标')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.app', verbose_name='APP特性属主')),
            ],
            options={
                'verbose_name': 'App特性列表',
                'verbose_name_plural': 'App特性列表',
            },
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='经历名称')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='子介绍名称')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(verbose_name='结束时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='经历属主')),
            ],
            options={
                'verbose_name': '个人经历',
                'verbose_name_plural': '个人经历',
            },
        ),
        migrations.CreateModel(
            name='eduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='学校名称')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('majer', models.CharField(max_length=100, verbose_name='专业')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(verbose_name='结束时间')),
                ('gpa', models.FloatField(blank=True, default=None, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='经历属主')),
            ],
            options={
                'verbose_name': '个人经历',
                'verbose_name_plural': '个人经历',
            },
        ),
        migrations.CreateModel(
            name='awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='奖励或证书介绍')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='奖励属主')),
            ],
            options={
                'verbose_name': '奖励或证书介绍',
                'verbose_name_plural': '奖励或证书介绍',
            },
        ),
    ]
