# Generated by Django 2.2.4 on 2019-10-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eduction',
            options={'verbose_name': '教育经历', 'verbose_name_plural': '教育经历'},
        ),
        migrations.AddField(
            model_name='experience',
            name='content',
            field=models.TextField(default='aaaaaaa', verbose_name='经历介绍'),
            preserve_default=False,
        ),
    ]
