# Generated by Django 2.2.4 on 2019-10-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191030_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='android_url',
            field=models.FileField(default='', upload_to='photos/%Y/%m/%d/', verbose_name='安卓下载地址'),
        ),
    ]
